Make migrations not crash at AddPageUrlToUploadMediaAssets.
Fixes this error:
    Migrating to AddPageURLToUploadMediaAssets (20220211075129)
       (0.4ms)  SELECT pg_advisory_unlock(7196913991661947245)
    rails aborted!
    NameError: uninitialized constant AddPageURLToUploadMediaAssets
    Did you mean?  AddPageUrlToUploadMediaAssets
                   AddColumnsToUploadMediaAssets

    Caused by:
    NameError: uninitialized constant AddPageURLToUploadMediaAssets
    Did you mean?  AddPageUrlToUploadMediaAssets
                   AddColumnsToUploadMediaAssets

    Tasks: TOP => db:prepare
    (See full trace by running task with --trace)